// Regenerates src/handlers/brotli_payload.ts. CompressionStream in Workers has
// no "br" variant, so the brotli body is precompressed here and shipped inline.
import { writeFileSync } from "node:fs";
import { brotliCompressSync } from "node:zlib";

const payload = brotliCompressSync(Buffer.from("uptimepage-mock brotli ok\n")).toString("base64");
const out = new URL("../src/handlers/brotli_payload.ts", import.meta.url);
writeFileSync(
  out,
  `// generated by scripts/gen-brotli.mjs — do not edit\nexport default ${JSON.stringify(payload)};\n`,
);
console.log(`wrote ${out.pathname} (${payload.length} b64 chars)`);
